version: "3.4"

services:
    app:
        image: naval_battle
        build:
            context: .
            dockerfile: devops/Dockerfile
        # env_file:
        # - .env
        network_mode: host
        ports:
            - "6700:6700"
        volumes:
            - .:/app
